### ISSUE TITLE
Smile string "c1cc[nH]c1" crashes Molecule constructor 

### ISSUE THREAD

**Issue by AndrewJamesTurner** [wtriddle/IFG#3]
Hi, 

I was using this library to calutate the functional groups for the the QM9 Quantum-Chemistry Dataset and found it crashed on the smile "c1cc[nH]c1".

Spcifically when the Molecule constructure called self.createVertices() which tried to look up "H" in REQUIRED_VALENCE_COUNTS (H is not pressant).

The error is:
`
File ".../chem/molecule.py", line 77, in __init__
    self.vertices: "list[Vertex]" = self.createVertices()
  File ".../chem/molecule.py", line 179, in createVertices
    valence_electrons_required=REQUIRED_VALENCE_COUNTS[symbol.upper()],
KeyError: 'H'
`

Any help would be apprecated :)

**Comment by wtriddle** [comment]
Hello,

The Molecule class uses hydrogen suppressed SMILES codes and does not currently support hydrogen symbols. Instead, it implicitly infers them. In this case, the SMILES code should be changed to c1ccnc1 and the code will function properly.
